apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: quickstart
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: hello-deployment
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 80
