[book]
# title = "xiaomlee's cookbook"
authors = ["小明大叔"]
language = "zh-CN"
multilingual = false
src = "./"

[build]
build-dir = "book"
create-missing = false
use-default-preprocessors = false

[preprocessor.links]
# renderers = ["html"]

[output.html]
mathjax-support = false
# theme = "theme"
curly-quotes = true
# google-analytics = "UA-128555056-1"
# additional-css = ["theme/custom.css"]
git-repository-url = "https://github.com/xiaomLee/my-cookbook"
gi-repository-icon = "fa-github"
edit-url-template = "https://github.com/xiaomLee/my-cookbook/edit/master/{path}"
# additional-js = ["theme/custom.js"]

# [output.linkcheck]
# follow-web-links = true
# traverse-parent-directories = false
# exclude = [ "google\\.com" ]

[output.html.playpen]
# editor = "./path/to/editor"
editable = false

[output.html.search]
enable = true
# searcher = "./path/to/searcher"
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
# copy-js = true