apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-nfs-tmp
spec:
  capacity:
    storage: 5Gi
  accessModes:
    # 在 PVC 绑定 PV 时通常根据两个条件来绑定，一个是存储的大小，另一个就是访问模式
    # RWO 是最基本的方式，可读可写，但只支持被单个节点挂载
    #- ReadWriteOnce 
    # ROX 可以以只读的方式被多个节点挂载
    #- ReadOnlyMany
    # RWX 这种存储可以以读写的方式被多个节点共享。不是每一种存储都支持这三种方式，像共享方式，目前支持的还比较少，比较常用的是NFS
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
    # Retain: 不清理, 保留 Volume; Recycle: 删除数据，即 rm -rf /thevolume/*（只有 NFS 和 HostPath 支持）; Delete: 删除存储资源，比如删除 AWS EBS 卷
  nfs:
    path: /nfs-root/tmp
    server: 172.16.41.132 # k8s-worker.local